const DATA_URL = "data/showcase-cases.csv";

const state = {
  cases: [],
  filters: {
    industry: "All",
    model: "All",
    subject: "All",
    search: "",
  },
};

const els = {
  grid: document.querySelector("#galleryGrid"),
  collectionStrip: document.querySelector("#collectionStrip"),
  industryFilter: document.querySelector("#industryFilter"),
  modelFilter: document.querySelector("#modelFilter"),
  subjectFilter: document.querySelector("#subjectFilter"),
  searchInput: document.querySelector("#searchInput"),
  resultCount: document.querySelector("#resultCount"),
  emptyState: document.querySelector("#emptyState"),
  resetFilters: document.querySelector("#resetFilters"),
  totalCases: document.querySelector("#totalCases"),
  totalModels: document.querySelector("#totalModels"),
  totalIndustries: document.querySelector("#totalIndustries"),
  dialog: document.querySelector("#caseDialog"),
  dialogContent: document.querySelector("#dialogContent"),
};

function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i += 1) {
    const char = text[i];
    const next = text[i + 1];

    if (char === '"' && inQuotes && next === '"') {
      cell += '"';
      i += 1;
      continue;
    }

    if (char === '"') {
      inQuotes = !inQuotes;
      continue;
    }

    if (char === "," && !inQuotes) {
      row.push(cell);
      cell = "";
      continue;
    }

    if ((char === "\n" || char === "\r") && !inQuotes) {
      if (char === "\r" && next === "\n") i += 1;
      row.push(cell);
      if (row.some(Boolean)) rows.push(row);
      row = [];
      cell = "";
      continue;
    }

    cell += char;
  }

  if (cell || row.length) {
    row.push(cell);
    rows.push(row);
  }

  const headers = rows.shift();
  return rows.map((values) => Object.fromEntries(headers.map((key, index) => [key, values[index] || ""])));
}

function unique(items, key) {
  return [...new Set(items.map((item) => item[key]).filter(Boolean))].sort();
}

function setOptions(select, values) {
  select.innerHTML = ["All", ...values]
    .map((value) => `<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`)
    .join("");
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function renderStats() {
  els.totalCases.textContent = state.cases.length;
  els.totalModels.textContent = unique(state.cases, "model").length;
  els.totalIndustries.textContent = unique(state.cases, "industry").length;
}

function renderCollections() {
  const industries = unique(state.cases, "industry");
  els.collectionStrip.innerHTML = industries
    .map((industry) => {
      const cases = state.cases.filter((item) => item.industry === industry);
      const subjects = unique(cases, "subject");
      return `
        <article class="collection-card">
          <h3>${escapeHtml(industry)}</h3>
          <p>${escapeHtml(subjects.slice(0, 4).join(" · "))}</p>
          <strong>${cases.length}</strong>
        </article>
      `;
    })
    .join("");
}

function applyFilters() {
  const query = state.filters.search.trim().toLowerCase();
  return state.cases.filter((item) => {
    const matchesIndustry = state.filters.industry === "All" || item.industry === state.filters.industry;
    const matchesModel = state.filters.model === "All" || item.model === state.filters.model;
    const matchesSubject = state.filters.subject === "All" || item.subject === state.filters.subject;
    const haystack = `${item.case_id} ${item.industry} ${item.subject} ${item.scene} ${item.model} ${item.prompt}`.toLowerCase();
    const matchesSearch = !query || haystack.includes(query);
    return matchesIndustry && matchesModel && matchesSubject && matchesSearch;
  });
}

function renderGallery() {
  const visibleCases = applyFilters();
  els.resultCount.textContent = `${visibleCases.length} case${visibleCases.length === 1 ? "" : "s"}`;
  els.emptyState.hidden = visibleCases.length > 0;
  els.grid.innerHTML = visibleCases
    .map((item, index) => `
      <article class="case-card">
        <img src="${escapeHtml(item.image)}" alt="${escapeHtml(`${item.scene} generated by ${item.model}`)}" loading="lazy">
        <div class="case-body">
          <div class="case-meta">
            <span class="tag">${escapeHtml(item.case_id)}</span>
            <span class="tag">${escapeHtml(item.subject)}</span>
            <span class="tag model">${escapeHtml(item.model)}</span>
          </div>
          <h3>${escapeHtml(item.scene)}</h3>
          <p>${escapeHtml(item.prompt.slice(0, 150))}${item.prompt.length > 150 ? "..." : ""}</p>
          <button type="button" data-index="${index}">View prompt</button>
        </div>
      </article>
    `)
    .join("");

  els.grid.querySelectorAll("button").forEach((button) => {
    button.addEventListener("click", () => openDialog(visibleCases[Number(button.dataset.index)]));
  });
}

function openDialog(item) {
  els.dialogContent.innerHTML = `
    <div class="dialog-layout">
      <img src="${escapeHtml(item.image)}" alt="${escapeHtml(`${item.scene} generated by ${item.model}`)}">
      <div class="dialog-info">
        <div class="case-meta">
          <span class="tag">${escapeHtml(item.industry)}</span>
          <span class="tag">${escapeHtml(item.subject)}</span>
          <span class="tag model">${escapeHtml(item.model)}</span>
        </div>
        <h2>${escapeHtml(item.scene)}</h2>
        <div class="prompt-box">${escapeHtml(item.prompt)}</div>
      </div>
    </div>
  `;
  els.dialog.showModal();
}

function wireFilters() {
  els.industryFilter.addEventListener("change", () => {
    state.filters.industry = els.industryFilter.value;
    renderGallery();
  });
  els.modelFilter.addEventListener("change", () => {
    state.filters.model = els.modelFilter.value;
    renderGallery();
  });
  els.subjectFilter.addEventListener("change", () => {
    state.filters.subject = els.subjectFilter.value;
    renderGallery();
  });
  els.searchInput.addEventListener("input", () => {
    state.filters.search = els.searchInput.value;
    renderGallery();
  });
  els.resetFilters.addEventListener("click", () => {
    state.filters = { industry: "All", model: "All", subject: "All", search: "" };
    els.industryFilter.value = "All";
    els.modelFilter.value = "All";
    els.subjectFilter.value = "All";
    els.searchInput.value = "";
    renderGallery();
  });
  document.querySelector(".dialog-close").addEventListener("click", () => els.dialog.close());
}

async function init() {
  const response = await fetch(DATA_URL);
  const csv = await response.text();
  state.cases = parseCsv(csv).filter((item) => item.status === "ok");

  setOptions(els.industryFilter, unique(state.cases, "industry"));
  setOptions(els.modelFilter, unique(state.cases, "model"));
  setOptions(els.subjectFilter, unique(state.cases, "subject"));
  renderStats();
  renderCollections();
  renderGallery();
  wireFilters();
}

init().catch((error) => {
  els.grid.innerHTML = `<p class="empty-state">Unable to load showcase data: ${escapeHtml(error.message)}</p>`;
});
